title: <p align = "center">Priyanka Patil</p>
logo: /assets/img/Priyanka_Photo_2.jpg
description: 
<p align="center">
<br>
Working as Senior Business Analyst at dcube Analytics Private Limited
</br>
</p>
theme: jekyll-theme-minimal
