title: Priyanka Patil
logo: /assets/img/Priyanka_Photo_2.jpg
description: Working as Senior Business Analyst at dcube Analytics Private Limited
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
