title: Minimal theme
logo: /assets/img/logo.png
description: I am Priyanka Patil,working as Senior Business analyst at Dcube analytics,have ovearall 3+ years of experience.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
